In [1]:
import torch

input = torch.tensor([[1,2,3], [4,5,6] , [7,8,9], [10,11,12]])

print(input.shape , input.shape[0], input.shape[1] , input.shape[-2], input.shape[-1])
print(input)


/Users/vusheshbabuadhikari/Learning/git/Building_LLM_from_scratch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


torch.Size([4, 3]) 4 3 4 3
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [4]:
input.T , input.transpose(-2,-1) , input.transpose(0,1) , input

(tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]),
 tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]),
 tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]),
 tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]))

In [10]:
input.shape

torch.Size([4, 3])

In [9]:
column_sum , row_sum = input.sum(dim= 0) , input.sum(dim=1) 
print("shape of column_sum: ", column_sum.shape) # Shape of the sum along rows (columns)
print("Sum along rows (dim=0): ", column_sum) # Sum along the first dimension (rows) - This will give us the sum of each column
print("shape of row_sum: ", row_sum.shape) # Shape of the sum along columns (rows)
print("Sum along columns (dim=1): ", row_sum) # Sum along the second dimension (columns) - This will give us the sum of each row

shape of column_sum:  torch.Size([3])
Sum along rows (dim=0):  tensor([22, 26, 30])
shape of row_sum:  torch.Size([4])
Sum along columns (dim=1):  tensor([ 6, 15, 24, 33])


In [ ]:
column_sum_keep_dim , row_sum_keep_dim = input.sum(dim= 0, keepdim=True) , input.sum(dim=1, keepdim=True) 
print("shape of column_sum_keep_dim: ", column_sum_keep_dim.shape) # Shape of the sum along rows (columns) with keepdim=True
print("Sum along rows (dim=0) with keepdim=True: ", column_sum_keep_dim) # Sum along the first dimension (rows) with keepdim=True - This will give us
# the sum of each column while keeping the original number of dimensions
print("shape of row_sum_keep_dim: ", row_sum_keep_dim.shape) # Shape of
# the sum along columns (rows) with keepdim=True
print("Sum" \
" along columns (dim=1) with keepdim=True: ", row_sum_keep_dim) # Sum along the second dimension (columns) with keepdim=True - This will give us
# the sum of each row while keeping the original number of dimensions

shape of column_sum_keep_dim:  torch.Size([1, 3])
Sum along rows (dim=0) with keepdim=True:  tensor([[22, 26, 30]])
shape of row_sum_keep_dim:  torch.Size([4, 1])
Sum along columns (dim=1) with keepdim=True:  tensor([[ 6],
        [15],
        [24],
        [33]])


In [19]:
torch.manual_seed(123) # Set random seed for reproducibility
embeddings = torch.nn.Embedding(num_embeddings=10, embedding_dim=5) # Create an embedding layer with 10 embeddings of dimension 5
input_indices = torch.tensor([0, 7, 8, 3]) # Example input indices
output_embeddings = embeddings(input_indices) # Get the corresponding embeddings for the input indices
print("Output embeddings for input indices [0, 7, 8, 3]: \n", output_embeddings)

print(embeddings.weight) # Shape of the input indices

Output embeddings for input indices [0, 7, 8, 3]: 
 tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486],
        [ 1.1331, -1.2203,  1.3139,  1.0533,  0.1388],
        [-0.2044, -2.2685, -0.2808,  0.7697, -0.6596],
        [ 0.2692, -0.0770, -1.0205, -0.1690,  0.9178]],
       grad_fn=<EmbeddingBackward0>)
Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486],
        [ 0.6603, -0.2196, -0.3792,  0.7671, -1.1925],
        [ 0.6984, -1.4097,  0.1794,  1.8951,  0.4954],
        [ 0.2692, -0.0770, -1.0205, -0.1690,  0.9178],
        [ 1.5810,  1.3010,  1.2753, -0.2010,  0.4965],
        [-1.5723,  0.9666, -1.1481, -1.1589,  0.3255],
        [-0.6315, -2.8400, -1.3250,  0.1784, -1.4779],
        [ 1.1331, -1.2203,  1.3139,  1.0533,  0.1388],
        [-0.2044, -2.2685, -0.2808,  0.7697, -0.6596],
        [-0.7979,  0.1838,  0.2293,  0.6177, -0.2876]], requires_grad=True)
