In [3]:
import torch

input = torch.tensor([[1,2,3], [4,5,6] , [7,8,9], [10,11,12]])

print(input.shape , input.shape[0], input.shape[1] , input.shape[-2], input.shape[-1])
print(input)


/Users/vusheshbabuadhikari/Learning/git/Building_LLM_from_scratch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


torch.Size([4, 3]) 4 3 4 3
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [4]:
input.T , input.transpose(-2,-1) , input.transpose(0,1) , input

(tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]),
 tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]),
 tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]),
 tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]))

In [5]:
input.shape

torch.Size([4, 3])

In [6]:
column_sum , row_sum = input.sum(dim= 0) , input.sum(dim=1) 
print("shape of column_sum: ", column_sum.shape) # Shape of the sum along rows (columns)
print("Sum along rows (dim=0): ", column_sum) # Sum along the first dimension (rows) - This will give us the sum of each column
print("shape of row_sum: ", row_sum.shape) # Shape of the sum along columns (rows)
print("Sum along columns (dim=1): ", row_sum) # Sum along the second dimension (columns) - This will give us the sum of each row

shape of column_sum:  torch.Size([3])
Sum along rows (dim=0):  tensor([22, 26, 30])
shape of row_sum:  torch.Size([4])
Sum along columns (dim=1):  tensor([ 6, 15, 24, 33])


In [7]:
column_sum_keep_dim , row_sum_keep_dim = input.sum(dim= 0, keepdim=True) , input.sum(dim=1, keepdim=True) 
print("shape of column_sum_keep_dim: ", column_sum_keep_dim.shape) # Shape of the sum along rows (columns) with keepdim=True
print("Sum along rows (dim=0) with keepdim=True: ", column_sum_keep_dim) # Sum along the first dimension (rows) with keepdim=True - This will give us
# the sum of each column while keeping the original number of dimensions
print("shape of row_sum_keep_dim: ", row_sum_keep_dim.shape) # Shape of
# the sum along columns (rows) with keepdim=True
print("Sum" \
" along columns (dim=1) with keepdim=True: ", row_sum_keep_dim) # Sum along the second dimension (columns) with keepdim=True - This will give us
# the sum of each row while keeping the original number of dimensions

shape of column_sum_keep_dim:  torch.Size([1, 3])
Sum along rows (dim=0) with keepdim=True:  tensor([[22, 26, 30]])
shape of row_sum_keep_dim:  torch.Size([4, 1])
Sum along columns (dim=1) with keepdim=True:  tensor([[ 6],
        [15],
        [24],
        [33]])


In [8]:
torch.manual_seed(123) # Set random seed for reproducibility
embeddings = torch.nn.Embedding(num_embeddings=10, embedding_dim=5) # Create an embedding layer with 10 embeddings of dimension 5
input_indices = torch.tensor([0, 7, 8, 3]) # Example input indices
output_embeddings = embeddings(input_indices) # Get the corresponding embeddings for the input indices
print("Output embeddings for input indices [0, 7, 8, 3]: \n", output_embeddings)

print(embeddings.weight) # Shape of the input indices

Output embeddings for input indices [0, 7, 8, 3]: 
 tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486],
        [ 1.1331, -1.2203,  1.3139,  1.0533,  0.1388],
        [-0.2044, -2.2685, -0.2808,  0.7697, -0.6596],
        [ 0.2692, -0.0770, -1.0205, -0.1690,  0.9178]],
       grad_fn=<EmbeddingBackward0>)
Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486],
        [ 0.6603, -0.2196, -0.3792,  0.7671, -1.1925],
        [ 0.6984, -1.4097,  0.1794,  1.8951,  0.4954],
        [ 0.2692, -0.0770, -1.0205, -0.1690,  0.9178],
        [ 1.5810,  1.3010,  1.2753, -0.2010,  0.4965],
        [-1.5723,  0.9666, -1.1481, -1.1589,  0.3255],
        [-0.6315, -2.8400, -1.3250,  0.1784, -1.4779],
        [ 1.1331, -1.2203,  1.3139,  1.0533,  0.1388],
        [-0.2044, -2.2685, -0.2808,  0.7697, -0.6596],
        [-0.7979,  0.1838,  0.2293,  0.6177, -0.2876]], requires_grad=True)


In [23]:
matrix = torch.triu(torch.ones(5,5), diagonal=1).bool() # Create an upper triangular matrix of ones with shape (5, 5
print("Upper triangular boolean matrix: \n", matrix)

# Create a tensor of shape (5, 5) filled with random values

inputs = torch.randn(5, 5) # Create a tensor of shape (5, 5) filled with random values
print("Input tensor: \n", inputs)

inputs_masked = inputs.masked_fill(matrix, float('-inf')) # Mask the upper triangular part of the input tensor using the boolean matrix
print("Input tensor after masking with upper triangular matrix: \n", inputs_masked)

Upper triangular boolean matrix: 
 tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])
Input tensor: 
 tensor([[ 0.2056, -0.4970,  0.5821,  0.2053, -0.9844],
        [ 1.9184,  0.9474,  1.6834,  0.4839, -1.3316],
        [ 0.2230,  0.6463,  0.1538, -0.4452,  0.5503],
        [ 0.0658,  0.6805, -0.1689, -0.5455,  0.2487],
        [ 0.1343,  0.7662,  2.2760, -1.3255, -0.8970]])
Input tensor after masking with upper triangular matrix: 
 tensor([[ 0.2056,    -inf,    -inf,    -inf,    -inf],
        [ 1.9184,  0.9474,    -inf,    -inf,    -inf],
        [ 0.2230,  0.6463,  0.1538,    -inf,    -inf],
        [ 0.0658,  0.6805, -0.1689, -0.5455,    -inf],
        [ 0.1343,  0.7662,  2.2760, -1.3255, -0.8970]])


In [24]:
dropout = torch.nn.Dropout(p=0.5) # Create a dropout layer with a dropout probability of 0.5
dropout_output = dropout(inputs) # Apply dropout to the input tensor
print("Output after applying dropout: \n", dropout_output)

Output after applying dropout: 
 tensor([[ 0.4112, -0.9939,  1.1641,  0.4106, -1.9687],
        [ 0.0000,  1.8948,  0.0000,  0.9677, -2.6632],
        [ 0.0000,  0.0000,  0.3076, -0.8903,  0.0000],
        [ 0.1316,  1.3610, -0.0000, -1.0910,  0.0000],
        [ 0.0000,  1.5325,  4.5521, -2.6511, -0.0000]])


In [28]:
combined = torch.stack([input, input], dim=0) # Stack the input tensor along a new dimension (dim=0) - This will create a new tensor with shape (2, 4, 3) by stacking two copies of the input tensor along the first dimension

In [36]:
input = torch.rand(2 , 4 , 4)
print(input)

input = input.view(2,4,2,2)

tensor([[[0.2346, 0.8188, 0.5773, 0.7870],
         [0.8855, 0.9941, 0.3705, 0.5148],
         [0.2103, 0.9562, 0.6591, 0.4172],
         [0.6253, 0.9961, 0.7036, 0.7429]],

        [[0.9616, 0.5214, 0.5024, 0.6241],
         [0.0379, 0.6748, 0.4962, 0.4761],
         [0.5288, 0.9429, 0.6435, 0.0470],
         [0.9632, 0.8049, 0.7523, 0.7063]]])


In [40]:
input.transpose(1,2)

tensor([[[[0.2346, 0.8188],
          [0.8855, 0.9941],
          [0.2103, 0.9562],
          [0.6253, 0.9961]],

         [[0.5773, 0.7870],
          [0.3705, 0.5148],
          [0.6591, 0.4172],
          [0.7036, 0.7429]]],


        [[[0.9616, 0.5214],
          [0.0379, 0.6748],
          [0.5288, 0.9429],
          [0.9632, 0.8049]],

         [[0.5024, 0.6241],
          [0.4962, 0.4761],
          [0.6435, 0.0470],
          [0.7523, 0.7063]]]])